name = "pendekin-router"
main = "src/index.ts"
compatibility_date = "2024-12-05"

compatibility_flags = ["nodejs_compat_v2"]

# [vars]
# MY_VAR = "my-variable"

routes = [
  { pattern = "azhe.my.id", custom_domain = true }
]

[env.staging]
workers_dev = true
route = "p-cf-stg.azhe.my.id/*"
API_BASE_URL = "https://console-stg.zizibot.nf.azhe.my.id"

[env.production]
workers_dev = true
route = "p-cf.azhe.my.id/*"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1
