name = "pendekin-router"
main = "src/index.ts"
compatibility_date = "2024-12-05"

compatibility_flags = ["nodejs_compat_v2"]

[placement]
mode = "smart"

[env.local]
workers_dev = true

[env.local.vars]
API_BASE_URL = "https://console-zizibot-dev.azhe.my.id"


[env.staging]
workers_dev = true
route = "p-cf-stg.azhe.my.id/*"

[env.staging.vars]
API_BASE_URL = "https://console-stg.zizibot.nf.azhe.my.id"


[env.production]
workers_dev = true
route = "p-cf.azhe.my.id/*"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1
