packages:
  - apps/*
  - packages/*
catalog:
  lucide-react: ^0.451.0
  tailwindcss: ^3.4.13
  eslint: ^8.57.0
  prettier: ^3.3.3
  typescript: ^5.6
  '@types/node': ^20
  '@types/eslint': ^8
  '@types/jest': ^29
  '@next/eslint-plugin-next': ^14
  next: ^14
  jest: ^29
  axios: ^1
catalogs:
  react18:
    react: ^18
    react-dom: ^18
    '@types/react': ^18
    '@types/react-dom': ^18
onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - workerd
