import '@zizibot/shadcn/globals.css';
import { ThemeProvider } from '@zizibot/shadcn/components/theme-provider';
import { Toaster } from '@zizibot/shadcn/components/ui/sonner';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React, { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Docs',
  description: 'Generated by create turbo'
};

export default function RootLayout(
  {
    children
  }: {
    children: ReactNode
  }) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <ThemeProvider
      attribute="class"
      defaultTheme="dark"
      enableSystem
      disableTransitionOnChange
    >
      {children}
    </ThemeProvider>
    <Toaster />
    </body>
    </html>
  );
}
